### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by NicoCG** [rebus-org/GoCommando#13]
Hi what is the status of this project is it depreciated?

**Comment by mookid8000** [comment]
I use it all the time 🙂just haven’t had time or good enough reasons to do any work on it

**Comment by mookid8000** [comment]
Anything you’re missing?

**Comment by NicoCG** [comment]
@mookid8000 Yes Migration to netstandard so I can use it in .netcore projects would be great.

I was previously using https://github.com/theouteredge/cmdR but when he stopped development on this project no support for netcore was an major issue for me.

**Comment by mookid8000** [comment]
See #12  😄 – unfortunately this is not something I need (for now) myself, so if I have to be realistic (I have to be that) I probably won't do anything about it anytime soon.

I'll be happy to help you submit a PR though, if you would like to help drive #12 forward.
