### ISSUE TITLE
[Question] LICENSE

### ISSUE THREAD

**Issue by NicoCG** [rebus-org/GoCommando#14]
Good day,

I would like to rewrite this library and change the name and add multiple functionality.
So I would like to use this library as template for my project.

I do see you use [beer-ware]http://en.wikipedia.org/wiki/Beerware License would you have any issues with me doing the above change the name and using this library as template for my project.

If you cool with this please provide me with the necessary credits you want shown on my project.

I ask this because normally when I use other peoples projects as templates that consist the beer-ware LICENCE they say 

> they do not care what I do, no credits necessary

**Comment by mookid8000** [comment]
I care about what you do: I think it would be cool, if you would rewrite it! 🥇 

You can do what you feel like – no attribution required or anything.

I would be happy though to see what you come up with 😄

**Comment by NicoCG** [comment]
Thank you I appreciate it I will show you once I have working library!

Starting off will not be anything special but I will start with migrating it to netstandard 👍
