### ISSUE TITLE
hej med dig

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/GoCommando#7]

**Comment by asgerhallas** [comment]
@mookid8000 hej med dig også!

**Comment by asgerhallas** [comment]
@mookid8000 I too wonder how this works...

**Comment by mookid8000** [comment]
@mookid8000 hej med dig også!

**Comment by mookid8000** [comment]
@mookid8000 I too wonder how this works...

**Comment by mookid8000** [comment]
@mookid8000 hej med dig også!

**Comment by mookid8000** [comment]
@mookid8000 I too wonder how this works...

**Comment by mookid8000** [comment]
@mookid8000 I too wonder how this works...
