### ISSUE TITLE
Throw exception when switch does not match

### ISSUE THREAD

**Issue by mookid8000** [rebus-org/GoCommando#9]
If the given switches matches the required arguments for the chosen command, the command is run even though additional switches might have been given.

This should not be possible, as it is most likely an indication that there is an error somewhere. A helpful exception should be thrown.

**Comment by t0mburton** [comment]
I'll take this one if that's ok.

**Comment by mookid8000** [comment]
👍👌😁

**Comment by t0mburton** [comment]
@mookid8000 Could you provide an example please? 

`beverage white-russian -vodka 1 -kahlua 12 -whiskey 10`

Seems to behave as you describe above and returns

```
The following switches do not have a corresponding parameter:

    -whiskey = 10
```

**Comment by mookid8000** [comment]
oh... that could be an indication that the described has in fact already been fixed.... just a moment!

**Comment by mookid8000** [comment]
sorry! [it seems this functionality has already been implemented)[https://github.com/rebus-org/GoCommando/blob/master/GoCommando/Internals/Command.cs#L117-L127] - I'm sorry if I confused you
